services:
  postgres:
    image: postgres:16
    container_name: event-management-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event-management
    volumes:
      - event-management-postgres-data:/var/lib/postgresql/data

volumes:
  event-management-postgres-data:
